=head1 NAME

App::arxiv2bib - Extract bibliographic data from the arXiv API

=head1 SYNOPSIS

    arxiv2bib [options] [args]

    arxiv2bib au:author1 AND au:author2 AND ti:title

    arxiv2bib --bibtex au:author1 ANDNOT ti:title

=head1 DESCRIPTION

The C<script/arxiv2bib> executable provided by the distribution extracts bibliographic information using the L<arXiv API|https://arxiv.org/help/api/user-manual>.

=head1 INSTALLATION

Using L<cpanm|https://metacpan.org/dist/App-cpanminus/view/bin/cpanm>: clone this repo, C<cd> into it, and then:

    $ cpanm .

Manual install:

    $ perl Makefile.PL
    $ make
    $ make install

=head1 OPTIONS

    -h | --help         usage examples and a breakdown of options/arguments
         --man          full documentation
    -n | --dry          only dump the the L<Mojo request object|https://docs.mojolicious.org/Mojo/Message/Request> your options have formed
    -v | --verbose	     	dump the entire L<Mojo response object|https://docs.mojolicious.org/Mojo/Message/Response> you've received

=head1 ARGUMENTS

ti 	Title

au 	Author

abs 	Abstract

co 	Comment

jr 	Journal Reference

cat 	Subject Category

rn 	Report Number

id 	Id (use id_list instead)

all 	All of the above
